name: Feature Request
description: Suggest an idea for TermuxHub
title: "[Feature Request]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature_description
    attributes:
      label: Describe your idea
      description: A clear and concise description of what you want to happen.
      placeholder: I would like to see...
    validations:
      required: true
